env:
  browser: true
  es2021: true
extends:
  - react-app
  - react-app/jest
  - plugin:react/recommended
  - standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ['./tsconfig.json']
plugins:
  - react
rules: {
  '@typescript-eslint/explicit-function-return-type': 'off',
  '@typescript-eslint/no-unused-vars': 'warn'
}
